Deneme/Controllers/CompanyOperationsController.cs
using Deneme.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Deneme.Controllers
{
    public class CompanyOperationsController : MyBaseController
    {

        [Authorize]
        public ActionResult COP_View()
        {

            return View();
        }

        [Authorize]
        public ActionResult COP()
        {

            using (YirmibesYazilimMutabakatEntities1 dc = new YirmibesYazilimMutabakatEntities1())
            {
                //string[] Keys = User.Identity.Name.Split(',');
                    int UserID = Convert.ToInt32(User.Identity.Name);
                    var company = dc.Company.Where(a => a.KullanıcıID == UserID).ToList();
                    return Json(new { data = company }, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpGet]
        [Authorize]
        public ActionResult AddOrEdit_COP(int id = 0)
        {
            if (id == 0)
                return View(new Company());
            else
            {
                using (YirmibesYazilimMutabakatEntities1 db = new YirmibesYazilimMutabakatEntities1())
                {
                    return View(db.Company.Where(x => x.CompanyId == id).FirstOrDefault<Company>());
                }
            }
        }

        [HttpPost]
        [Authorize]
        public ActionResult AddOrEdit_COP(Company company)
        {
            //string[] Keys = User.Identity.Name.Split(',');
            int UserID = Convert.ToInt32(User.Identity.Name);
            using (YirmibesYazilimMutabakatEntities1 db = new YirmibesYazilimMutabakatEntities1())
            {
                company.KullanıcıID = UserID;
                if (company.CompanyId == 0)
                {
                    db.Company.Add(company);
                    db.SaveChanges();
                    return Json(new { success = true, message = Deneme.Resource.SavedSuccessfully }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    db.Entry(company).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    return Json(new { success = true, message = Deneme.Resource.UpdatedSuccessfully }, JsonRequestBehavior.AllowGet);
                }
            }
        }

        [HttpPost]
        [Authorize]
        public ActionResult Delete_COP(int id)
        {
            using (YirmibesYazilimMutabakatEntities1 db = new YirmibesYazilimMutabakatEntities1())
            {
                Company company = db.Company.Where(x => x.CompanyId == id).FirstOrDefault<Company>();
                db.Company.Remove(company);
                db.SaveChanges();
                return Json(new { success = true, message = Deneme.Resource.DeletedSuccessfully }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        [Authorize]
        public ActionResult Select_COP(int id)
        {
            string isAdmin = Server.HtmlEncode(Request.Cookies["UserOp"]["isAdmin"]);
            
            string Yetki = Server.HtmlEncode(Request.Cookies["UserOp"]["Yetki"]);
            if (isAdmin == "0")
            {
                string SubUserId = Server.HtmlEncode(Request.Cookies["UserOp"]["SubId"]);
                Response.Cookies["UserOp"]["SubId"] = SubUserId;
            }
            Response.Cookies["UserOp"]["CompanyId"] = id.ToString();

            Response.Cookies["UserOp"]["Yetki"] = Yetki;
            Response.Cookies["UserOp"]["isAdmin"] = isAdmin;
            Response.Cookies["UserOp"].Expires = DateTime.Now.AddMinutes(20);
            return Json(new { success = true, message = Deneme.Resource.CompanySelectedSuccesfully }, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public ActionResult SubCOP_View()
        {

            return View();
        }
        [HttpGet]
        [Authorize]
        public ActionResult SubCOP()
        {

            using (YirmibesYazilimMutabakatEntities1 db = new YirmibesYazilimMutabakatEntities1())
            {
                int SubId = Convert.ToInt32(Server.HtmlEncode(Request.Cookies["UserOp"]["SubId"]));
                var yetki = db.Yetki.Where(x => x.UserID == SubId).ToList();
                List<Company> company = new List<Company>();
                foreach (var item in yetki)
                {
                    company.Add(db.Company.Where(x => x.CompanyId == item.CompanyId).FirstOrDefault());
                }
                return Json(new { data = company }, JsonRequestBehavior.AllowGet);
            }

        }



    }
}

Deneme/Views/CompanyOperations/AddOrEdit_COP.cshtml
@model Deneme.Models.Company
@{
    Layout = null;
}

    @using (Html.BeginForm("AddOrEdit_COP", "CompanyOperations", FormMethod.Post, new { onsubmit = "return SubmitForm(this)" }))
    {
        @Html.HiddenFor(model => model.CompanyId)
        <div class="block push-bit">

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <form>
                <div class="form-row">
                    <div class="form-group col-md-12">
                        <label class="control-label " for="CompanyTitle"> @Deneme.Resource.CompanyTitle *</label>
                        @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "required form-control" } })
                        @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label class="control-label " for="TaxOffice"> @Deneme.Resource.TaxOffice *</label>
                        @Html.EditorFor(model => model.TaxOffice, new { htmlAttributes = new { @class = "required form-control" } })
                        @Html.ValidationMessageFor(model => model.TaxOffice, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-6">
                        <label class="control-label " for="TaxNumber"> @Deneme.Resource.TaxNumber *</label>
                        @Html.EditorFor(model => model.TaxNo_TcNo, new { htmlAttributes = new { @class = "required form-control" } })
                        @Html.ValidationMessageFor(model => model.TaxNo_TcNo, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label class="control-label " for="PhoneNumber"> @Deneme.Resource.PhoneNumber *</label>
                        @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "required form-control" } })
                        @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-6">
                        <label class="control-label " for="FaxNumber"> @Deneme.Resource.FaxNumber *</label>
                        @Html.EditorFor(model => model.FaxNumber, new { htmlAttributes = new { @class = "required form-control" } })
                        @Html.ValidationMessageFor(model => model.FaxNumber, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label class="control-label " for="Country"> @Deneme.Resource.Country *</label>
                        @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "required form-control" } })
                        @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-4">
                        <label class="control-label " for="City"> @Deneme.Resource.City *</label>
                        @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "required form-control" } })
                        @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-4">
                        <label class="control-label " for="State"> @Deneme.Resource.State *</label>
                        @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "required form-control" } })
                        @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-12">
                        <label class="control-label " for="Address"> @Deneme.Resource.Address *</label>
                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "required form-control" } })
                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group text-center m-t-15 ">
                    <button class="btn btn-danger btn-block text-uppercase waves-effect waves-light"
                            type="submit">
                        @Deneme.Resource.Save
                    </button>
                </div>
            </form>
        </div>

    }

Deneme/Views/CompanyOperations/COP_View.cshtml
@{
    ViewBag.Title = "Company Operations";
}
<body>
    <div class="row">
        <div class="col-sm-12">
            <div class="page-title-box">
                <div class="btn-group pull-right">
                    <ol class="breadcrumb hide-phone p-0 m-0">
                        <li class="breadcrumb-item"><a href="#">Mutabakatcim</a></li>

                        <li class="breadcrumb-item active">@Deneme.Resource.CompanyOperations</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <br />
    <a class="btn btn-success" style="margin-bottom:10px;" onclick="PopupForm('@Url.Action("AddOrEdit_COP", "CompanyOperations")')"><i class="fa fa-plus"></i> @Deneme.Resource.AddNew</a>
    <table id="BillTemplate" class="display nowrap table table-striped table-bordered" style="width:100%;">
        <thead>
            <tr>

                <th data-priority="2">@Deneme.Resource.CompanyTitle</th>
                <th data-priority="3">@Deneme.Resource.TaxOffice</th>
                <th>@Deneme.Resource.TaxNumber</th>
                <th>@Deneme.Resource.PhoneNumber</th>
                <th>@Deneme.Resource.FaxNumber</th>
                <th>@Deneme.Resource.Address</th>
                <th>@Deneme.Resource.State</th>
                <th>@Deneme.Resource.City</th>
                <th>@Deneme.Resource.Country</th>
                <th data-priority="1"></th>

            </tr>
        </thead>
    </table>


    @section scripts{

        <script>
        var Popup, dataTable;
        $(document).ready(function () {
            responsive: true
            dataTable = $("#BillTemplate").DataTable({
                responsive: {
                    details: {
                        renderer: function (api, rowIdx, columns) {
                            var data = $.map(columns, function (col, i) {
                                return col.hidden ?
                                    '<tr data-dt-row="' + col.rowIndex + '" data-dt-column="' + col.columnIndex + '">' +
                                    '<td>' + col.title + ':' + ' </td> ' +
                                    '<td>' + col.data + ' </td>' +
                                    '</tr>' :
                                    '';
                            }).join('');

                            return data ?
                                $('<table/>').append(data) :
                                false;
                        }
                    }
                },
                "ajax": {
                    "url": "/CompanyOperations/COP",
                    "type": "GET",
                    "datatype": "json",
                    "style":"margin-left:50px"
                },
                "columns": [
                    { "data": "CompanyName" },
                    { "data": "TaxOffice" },
                    { "data": "TaxNo_TcNo" },
                    { "data": "PhoneNumber" },
                    { "data": "FaxNumber" },
                    { "data": "Address" },
                    { "data": "State" },
                    { "data": "City" },
                    { "data": "Country" },
                    {"data":"CompanyId" , "render" : function (data) {
                        return "<a class='btn btn-default btn-sm' onclick=PopupForm('@Url.Action("AddOrEdit_COP", "CompanyOperations")/" + data + "')><i class='fa fa-pencil'></i> @Deneme.Resource.Edit</a><a class='btn btn-danger btn-sm' style='margin-left:5px' onclick=Delete("+data+")><i class='fa fa-trash'></i> @Deneme.Resource.Delete</a><a class='btn btn-primary btn-sm' style='margin-left:5px' onclick=Select("+data+")><i class='fa fa-heart'></i> @Deneme.Resource.SelectCompany</a>";
                    },
                        "orderable": false,
                        "searchable": false,
                        "width":"150px"
                    }

                ],
                "language": {

                    "info": "@Deneme.Resource.Info",
                    "infoEmpty": "@Deneme.Resource.InfoEmpty",
                    "infoFiltered": "@Deneme.Resource.InfoFiltered",
                    "lengthMenu": "@Deneme.Resource.LengthMenu",
                    "loadingRecords": "@Deneme.Resource.LoadingRecords",
                    "zeroRecords": "@Deneme.Resource.ZeroRecords",
                    "search": "@Deneme.Resource.Search",
                    "emptyTable": "@Deneme.Resource.EmptyTable1 <b>@Deneme.Resource.AddNew</b>  @Deneme.Resource.EmptyTable2",
                    "paginate": {

                        "next": "@Deneme.Resource.Next",
                        "previous": "@Deneme.Resource.Previous"
                    },
                }
            });
        });

        function PopupForm(url) {
            var formDiv = $('<div/>');
            $.get(url)
            .done(function (response) {
                formDiv.html(response);

                Popup = formDiv.dialog({
                    show: {
                        effect: "blind",
                        duration: 600
                    },
                    hide: {
                        effect: "blind",
                        duration: 600
                    },
                    modal: true,
                    responsive: true,
                    autoOpen: true,
                    resizable: true,
                    title: '@Deneme.Resource.DialogCompanyOperations',
                    height: 420,
                    width: 900,
                    close: function () {
                        Popup.dialog('destroy').remove();
                    }
                });
            });
        }

        function SubmitForm(form) {
            $.validator.unobtrusive.parse(form);
            if($(form).valid()){
                $.ajax({
                    type : "POST",
                    url : form.action,
                    data : $(form).serialize(),
                    success : function (data) {
                        if(data.success)
                        {
                            Popup.dialog('close');
                            dataTable.ajax.reload();

                            $.notify(data.message,{
                                globalPosition :"top center",
                                className : "success"
                            })

                        }
                    }
                });
            }
            return false;
        }

        function Delete(id) {
            if(confirm('@Deneme.Resource.DeleteConfirmation'))
            {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Delete_COP", "CompanyOperations")/' + id,
                    success: function (data) {
                        if (data.success)
                        {
                            dataTable.ajax.reload();

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            })

                        }
                    }

                });
            }
        }
        function Select(id) {

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Select_COP", "CompanyOperations")/' + id,
                    success: function (data) {
                        if (data.success)
                        {
                            //dataTable.ajax.reload();
                            location.reload();
                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            })

                        }
                    }

                });
        }


        </script>
    }
</body>

Deneme/Views/CompanyOperations/SubCOP_View.cshtml
@{
    ViewBag.Title = "Company Operations";
}
<body>
    <div class="row">
        <div class="col-sm-12">
            <div class="page-title-box">
                <div class="btn-group pull-right">
                    <ol class="breadcrumb hide-phone p-0 m-0">
                        <li class="breadcrumb-item"><a href="#">Mutabakatcim</a></li>

                        <li class="breadcrumb-item active">@Deneme.Resource.CompanyOperations</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <br />
    <table id="BillTemplate" class="display nowrap table table-striped table-bordered" style="width:100%;">
        <thead>
            <tr>

                <th data-priority="2">@Deneme.Resource.CompanyTitle</th>
                <th data-priority="3">@Deneme.Resource.TaxOffice</th>
                <th>@Deneme.Resource.TaxNumber</th>
                <th>@Deneme.Resource.PhoneNumber</th>
                <th>@Deneme.Resource.FaxNumber</th>
                <th>@Deneme.Resource.Address</th>
                <th>@Deneme.Resource.State</th>
                <th>@Deneme.Resource.City</th>
                <th>@Deneme.Resource.Country</th>
                <th data-priority="1"></th>

            </tr>
        </thead>
    </table>


    @section scripts{

        <script>
        var  dataTable;
        $(document).ready(function () {
            responsive: true
            dataTable = $("#BillTemplate").DataTable({
                responsive: {
                    details: {
                        renderer: function (api, rowIdx, columns) {
                            var data = $.map(columns, function (col, i) {
                                return col.hidden ?
                                    '<tr data-dt-row="' + col.rowIndex + '" data-dt-column="' + col.columnIndex + '">' +
                                    '<td>' + col.title + ':' + ' </td> ' +
                                    '<td>' + col.data + ' </td>' +
                                    '</tr>' :
                                    '';
                            }).join('');

                            return data ?
                                $('<table/>').append(data) :
                                false;
                        }
                    }
                },
                "ajax": {
                    "url": "/CompanyOperations/SubCOP",
                    "type": "GET",
                    "datatype": "json",
                    "style":"margin-left:50px"
                },
                "columns": [
                    { "data": "CompanyName" },
                    { "data": "TaxOffice" },
                    { "data": "TaxNo_TcNo" },
                    { "data": "PhoneNumber" },
                    { "data": "FaxNumber" },
                    { "data": "Address" },
                    { "data": "State" },
                    { "data": "City" },
                    { "data": "Country" },
                    {"data":"CompanyId" , "render" : function (data) {
                        return "<a class='btn btn-primary btn-sm' style='margin-left:5px' onclick=Select("+data+")><i class='fa fa-heart'></i> @Deneme.Resource.SelectCompany</a>";
                    },
                        "orderable": false,
                        "searchable": false,
                        "width":"150px"
                    }

                ],
                "language": {

                    "info": "@Deneme.Resource.Info",
                    "infoEmpty": "@Deneme.Resource.InfoEmpty",
                    "infoFiltered": "@Deneme.Resource.InfoFiltered",
                    "lengthMenu": "@Deneme.Resource.LengthMenu",
                    "loadingRecords": "@Deneme.Resource.LoadingRecords",
                    "zeroRecords": "@Deneme.Resource.ZeroRecords",
                    "search": "@Deneme.Resource.Search",
                    "emptyTable": "@Deneme.Resource.EmptyTable1 <b>@Deneme.Resource.AddNew</b>  @Deneme.Resource.EmptyTable2",
                    "paginate": {

                        "next": "@Deneme.Resource.Next",
                        "previous": "@Deneme.Resource.Previous"
                    },
                }
            });
        });

        function Select(id) {

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Select_COP", "CompanyOperations")/' + id,
                    success: function (data) {
                        if (data.success)
                        {
                            dataTable.ajax.reload();

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            })

                        }
                    }

                });
        }


        </script>
    }
</body>