Deneme/Controllers/BaBsReconciliationController.cs
using Deneme.Models;
using ExcelDataReader;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;

namespace Deneme.Controllers
{
    public class BaBsReconciliationController : MyBaseController
    {

        #region Show BaBs Excel
        [HttpGet]
        [Authorize]
        public ActionResult Show_BaBsExcelView(int id)
        {

            using (YirmibesYazilimMutabakatEntities1 dc = new YirmibesYazilimMutabakatEntities1())
            {
                var v = dc.BaBsMutabakatExcel.Where(a => a.MutabakatBilgileriId == id).ToList();
                var jsonResult = Json(new { data = v }, JsonRequestBehavior.AllowGet);
                jsonResult.MaxJsonLength = int.MaxValue;
                return jsonResult;
            }

        }

        [HttpGet]
        [Authorize]
        public ActionResult Show_BaBsExcel(int id)
        {
            ViewBag.FaturaId = id;
            return View();

        }
        #endregion

        #region Add BaBsExcel
        [HttpGet]
        [Authorize]
        public ActionResult Add_BaBsExcel()
        {
            using (YirmibesYazilimMutabakatEntities1 dc = new YirmibesYazilimMutabakatEntities1())
            {

                //string Keys = User.Identity.Name.Split(',');
                int UserID = Convert.ToInt32(User.Identity.Name);
                int SelectedCompanyID = Convert.ToInt32(Server.HtmlEncode(Request.Cookies["UserOp"]["CompanyId"]));
                //if (Session["SelectedCompanyID"] != null)
                //{
                //    SelectedCompanyID = Convert.ToInt32(Session["SelectedCompanyID"]);
                //}
                //else
                //{
                //    SelectedCompanyID = Convert.ToInt32(Keys[1]);
                //}
                var BaBsŞablon = dc.Şablon_Ba_BsMutabakat.Where(a => a.KullanıcıId == UserID && a.CompanyId == SelectedCompanyID).ToList();

                List<int> Yıl = new List<int> { 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018 };

                ViewBag.Yıl = Yıl;
                List<SelectListItem> ŞablonId = (from item in BaBsŞablon
                                                 select new SelectListItem
                                                 {
                                                     Text = item.ŞablonAdı,
                                                     Value = item.ŞablonId.ToString()
                                                 }).ToList();


                ViewBag.ŞablonId = ŞablonId;

                return View();
            }
        }

        [HttpPost]
        [Authorize]
        public ActionResult Add_BaBsExcel(HttpPostedFileBase excelfile, BaBsMutabakatBilgileri fatura)
        {
            var bal = @Server.HtmlEncode(Request.Cookies["UserOp"]["Yetki"]).ToString().Split(',')[0];
            var bsat = @Server.HtmlEncode(Request.Cookies["UserOp"]["Yetki"]).ToString().Split(',')[5];
            var FaturaTipi = fatura.FaturaTipi;

            if (bal == "1" && FaturaTipi == "Alış" || bsat == "1" && FaturaTipi == "Satış")
            {
                if (excelfile == null || excelfile.ContentLength == 0)
                {
                    ViewBag.Error = "Please select a excel file <br>";
                    return View("Index");
                }
                else
                {
                    if (excelfile.FileName.EndsWith("xls") || excelfile.FileName.EndsWith("xlsx"))
                    {


                        using (YirmibesYazilimMutabakatEntities1 dc = new YirmibesYazilimMutabakatEntities1())
                        {
                            #region Getting session informations
                            //string[] Keys = User.Identity.Name.Split(',');
                            int UserID = Convert.ToInt32(User.Identity.Name);
                            int SelectedCompanyID = Convert.ToInt32(Server.HtmlEncode(Request.Cookies["UserOp"]["CompanyId"]));
                            //if (Session["SelectedCompanyID"] != null)
                            //{
                            //    SelectedCompanyID = Convert.ToInt32(Session["SelectedCompanyID"]);
                            //}
                            //else
                            //{
                            //    SelectedCompanyID = Convert.ToInt32(Keys[1]);
                            //}
                            var şablon = dc.Şablon_Ba_BsMutabakat.Where(a => a.ŞablonId == fatura.ŞablonId).FirstOrDefault();
                            #endregion

                            #region Save bill details
                            fatura.KullanıcıId = UserID;
                            fatura.CompanyId = SelectedCompanyID;
                            fatura.ExcelAdı = excelfile.FileName;
                            fatura.ŞablonAdı = şablon.ŞablonAdı;
                            fatura.OluşturmaTarihi = Convert.ToString(DateTime.Now);
                            dc.BaBsMutabakatBilgileri.Add(fatura);
                            dc.SaveChanges();
                            #endregion

                            #region Getting excel column names

                            int bs = (şablon.BelgeSayısı)[0] - 65;
                            int ca = (şablon.CariAdı)[0] - 65;
                            int ck = (şablon.CariKodu)[0] - 65;
                            int t = (şablon.KdvHariçTutar)[0] - 65;
                            int tc = (şablon.TcKimlikNo)[0] - 65;
                            int vn = (şablon.VergiNo)[0] - 65;
                            #endregion
                            try
                            {
                                string path = Server.MapPath("~/Content/" + excelfile.FileName);

                                #region Checking file is exist
                                if (System.IO.File.Exists(path))
                                {
                                    System.IO.File.Delete(path);
                                }
                                #endregion

                                excelfile.SaveAs(path);

                                #region File Operations
                                FileStream fs = new FileStream(path, FileMode.Open);
                                IExcelDataReader excelReader;
                                if (excelfile.FileName.EndsWith("xls"))
                                {
                                    excelReader = ExcelReaderFactory.CreateBinaryReader(fs);
                                }
                                else
                                {
                                    excelReader = ExcelReaderFactory.CreateOpenXmlReader(fs);
                                }
                                #endregion


                                try
                                {
                                    #region Transfer excel to dataset
                                    DataSet excelDS = excelReader.AsDataSet();
                                    DataTable excel = excelDS.Tables[0];
                                    DataTable copyExcel = excel.Clone();
                                    copyExcel.Columns[t].DataType = typeof(Double);

                                    DataColumn dcolColumn = new DataColumn("MutabakatBilgileriId", typeof(Int32));
                                    dcolColumn.DefaultValue = fatura.MutabakatBilgileriId;
                                    copyExcel.Columns.Add(dcolColumn);

                                    int başlangıçSatırı = 1;
                                    foreach (DataRow row in excel.Rows)
                                    {
                                        try
                                        {
                                            if (başlangıçSatırı >= şablon.BaşlangıçSatırı)
                                            {
                                                copyExcel.ImportRow(row);
                                            }
                                            başlangıçSatırı++;
                                        }
                                        catch(Exception)
                                        {
                                            BaBsMutabakatBilgileri baBsMutabakatBilgileri = dc.BaBsMutabakatBilgileri.Where(x => x.MutabakatBilgileriId == fatura.MutabakatBilgileriId).FirstOrDefault<BaBsMutabakatBilgileri>();
                                            dc.BaBsMutabakatBilgileri.Remove(baBsMutabakatBilgileri);
                                            //dc.CariBilgileriExcel.RemoveRange(dc.CariBilgileriExcel.Where(x => x.CariBilgileriId == cari.CariBilgileriId));
                                            dc.SaveChanges();
                                            return Json(new { success = false, message = Deneme.Resource.SqlExeption }, JsonRequestBehavior.AllowGet);

                                        }
                                    }
                                    excelReader.Close();
                                    #endregion

                                    #region Deleting unnecessary columns

                                    for (int i = 0; i < excel.Columns.Count; i++)
                                    {

                                        if (i != bs && i != ca && i != ck && i != t && i != tc && i != vn)
                                        {
                                            copyExcel.Columns.Remove("Column" + i);

                                        }


                                    }
                                    #endregion

                                    try
                                    {

Deneme/Views/BaBsReconciliation/Add_BaBsExcel.cshtml
@model Deneme.Models.BaBsMutabakatBilgileri
@{

    Layout = null;
}
<html>
<body>

    @using (Html.BeginForm("Add_BaBsExcel", "BaBsReconciliation", FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "return SubmitForm(this)" }))
    {
        @Html.HiddenFor(model => model.MutabakatBilgileriId)
        <div class="block push-bit">

            <p class="text-info m-b-15 font-13">
                @Deneme.Resource.AddBaBsExcel
            </p>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <form>
                <div class="form-row">
                    <div class="form-group col-md-6">

                        @Html.DropDownList("Ay", new SelectList(Enum.GetValues(typeof(Deneme.Models.BaBsMutabakatBilgileri.Months))), Deneme.Resource.SelectInvoiceMonth, new
                   {
                       @class = "form-control",
                       @required = "",
                       oninvalid = "this.setCustomValidity(" + "'" + @Deneme.Resource.Required + "'" + ")",
                       oninput = "setCustomValidity('')"
                   })
                        @Html.ValidationMessageFor(model => model.Ay, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group col-md-6">

                        @Html.DropDownList("Yıl", new SelectList(ViewBag.Yıl), Deneme.Resource.SelectInvoiceYear, new
                   {
                       @class = "form-control",
                       @required = "",
                       oninvalid = "this.setCustomValidity(" + "'" + @Deneme.Resource.Required + "'" + ")",
                       oninput = "setCustomValidity('')"
                   })
                        @Html.ValidationMessageFor(model => model.Yıl, "", new { @class = "text-danger" })

                    </div>

                </div>
                <div class="form-row">
                    <div class="form-group col-md-5">

                        @Html.DropDownList("FaturaTipi", new SelectList(Enum.GetValues(typeof(Deneme.Models.BaBsMutabakatBilgileri.Tip))), Deneme.Resource.SelectInvoiceType, new
                   {
                       @class = "form-control",
                       @required = "",
                       oninvalid = "this.setCustomValidity(" + "'" + @Deneme.Resource.Required + "'" + ")",
                       oninput = "setCustomValidity('')"
                   })
                        @Html.ValidationMessageFor(model => model.FaturaTipi, "", new { @class = "text-danger" })

                    </div>


                    <div class="form-group col-md-7">

                        @Html.DropDownList("ŞablonId", null, Deneme.Resource.SelectTemplateName, new
                   {
                       @class = "form-control",
                       @required = "",
                       oninvalid = "this.setCustomValidity(" + "'" + @Deneme.Resource.Required + "'" + ")",
                       oninput = "setCustomValidity('')"
                   })
                        @Html.ValidationMessageFor(model => model.ŞablonId, "", new { @class = "text-danger" })

                    </div>

                </div>
                <div class="form-row">
                    <div class="form-group m-b-0 col-md-12">

                        <input type="file" data-buttonText="@Deneme.Resource.ChooseFile" class="filestyle" data-placeholder="@Deneme.Resource.NoFile" name="excelfile" data-buttonname="btn-danger" data-iconname="fa fa-cloud-upload" required oninvalid = "this.setCustomValidity('@Deneme.Resource.SelectFile')",
               oninput = "setCustomValidity('')">
                    </div>
                </div>
                <div class="form-group  m-t-15">
                    <div class=" progress progress-bar-info" role="progressbar" aria-valuenow="95" aria-valuemin="0" aria-valuemax="100" id="progressbar" style="position: relative; display: none">
                        <span class="sr-only" style="position: center; left: 35%; top: 50%" id="progressBar-label">
                            @Deneme.Resource.Uploading
                        </span>
                    </div>
                </div>
                <div class="form-group text-center m-t-15 ">
                    <button class="btn btn-danger btn-block text-uppercase waves-effect waves-light" type="submit">
                        @Deneme.Resource.Save
                    </button>
                </div>

            </form>
        </div>
        <script src="~/assets/js/bootstrap-filestyle.min.js"></script>
    }
</body>
</html>

Deneme/Views/BaBsReconciliation/BaBsExcel_View.cshtml
@{
    ViewBag.Title = "Faturalarım";
}
<body>

        <div class="row">
            <div class="col-sm-12">
                <div class="page-title-box">
                    <div class="btn-group pull-right">
                        <ol class="breadcrumb hide-phone p-0 m-0">
                            <li class="breadcrumb-item"><a href="#">Mutabakatcim</a></li>
                            <li class="breadcrumb-item"><a href="@Url.Action("BaBsMY_View", "Reconciliation")">@Deneme.Resource.Reconciliation</a></li>
                            <li class="breadcrumb-item active">Excelden Mutabakat Oluştur</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <br />

            <a class="btn btn-success" style="margin-bottom:10px;" onclick="PopupForm('@Url.Action("Add_BaBsExcel", "BaBsReconciliation")')"><i class="fa fa-plus"></i> @Deneme.Resource.AddNew </a>
            <table id="BillTemplate" class="display nowrap table table-striped table-bordered" style="width:100%;">
                <thead>
                    <tr>
                        <th data-priority="1">@Deneme.Resource.ExcelName</th>
                        <th data-priority="2">@Deneme.Resource.Month</th>
                        <th data-priority="3">@Deneme.Resource.Year</th>
                        <th>@Deneme.Resource.TemplateName</th>
                        <th>@Deneme.Resource.ReconciliationType</th>
                        <th>@Deneme.Resource.TemplateCreationDate</th>
                        <th data-priority="4"></th>
                    </tr>
                </thead>
            </table>
            @section scripts{
                <script>
        var Popup, dataTable;
           $(document).ready(function () {
               dataTable = $("#BillTemplate").DataTable({
                   responsive: {
                       details: {
                           renderer: function (api, rowIdx, columns) {
                               var data = $.map(columns, function (col, i) {
                                   return col.hidden ?
                                       '<tr data-dt-row="' + col.rowIndex + '" data-dt-column="' + col.columnIndex + '">' +
                                       '<td>' + col.title + ':' + ' </td> ' +
                                       '<td>' + col.data + ' </td>' +
                                       '</tr>' :
                                       '';
                               }).join('');

                               return data ?
                                   $('<table/>').append(data) :
                                   false;
                           }
                       }
                   },
                "ajax": {
                    "url": "/BaBsReconciliation/BaBsExcel",
                    "type": "GET",
                    "datatype": "json",
                    "style":"margin-left:50px"
                },
                "columns": [
                    { "data": "ExcelAdı" },
                    { "data": "Ay" },
                    { "data": "Yıl" },
                    { "data": "ŞablonAdı" },
                    { "data": "FaturaTipi" },
                    { "data": "OluşturmaTarihi" },
                    { "data":"MutabakatBilgileriId" , "render" : function (data) {
                        return "<a class='btn btn-info btn-sm' onclick=Show(" + data +")><i class='fa fa-eye'></i> @Deneme.Resource.Show</a><a class='btn btn-danger btn-sm' style='margin-left:5px' onclick=Delete("+data+")><i class='fa fa-trash'></i> @Deneme.Resource.Delete </a>";
                    },
                        "destroy": true,
                        "orderable": false,
                        "searchable":false,
                        "width":"150px"
                    }

                ],
                "language": {

                    "info": "@Deneme.Resource.Info",
                    "infoEmpty": "@Deneme.Resource.InfoEmpty",
                    "infoFiltered": "@Deneme.Resource.InfoFiltered",
                    "lengthMenu": "@Deneme.Resource.LengthMenu",
                    "loadingRecords": "@Deneme.Resource.LoadingRecords",
                    "zeroRecords": "@Deneme.Resource.ZeroRecords",
                    "search": "@Deneme.Resource.Search",
                    "emptyTable": "@Deneme.Resource.EmptyTable1 <b>@Deneme.Resource.AddNew</b>  @Deneme.Resource.EmptyTable2",
                    "paginate": {

                        "next": "@Deneme.Resource.Next",
                        "previous": "@Deneme.Resource.Previous"
                    },
                }
            });
        });

        function PopupForm(url) {
            var formDiv = $('<div/>');
            $.get(url)
            .done(function (response) {
                formDiv.html(response);

                Popup = formDiv.dialog({
                    show: {
                        effect: "blind",
                        duration: 600
                    },
                    hide: {
                        effect: "blind",
                        duration: 600
                    },
                    globalPosition: 'absolute',
                    modal: true,
                    responsive: true,
                    autoOpen: true,
                    resizable: true,
                    title: '@Deneme.Resource.DialogBaBs',
                    height: 330,
                    width: 700,
                    close: function () {
                        Popup.dialog('destroy').remove();
                    }

                });
            });
        }
        function SubmitForm(form) {
            $.validator.unobtrusive.parse(form);
            if ($(form).valid()) {
                var formData = new FormData($(form)[0]);
                var progressbarLabel = $('#progressBar-label');
                var progressbarDiv = $('#progressbar');

                $.ajax({
                    url: form.action,
                    type: form.method,
                    data: formData,
                    processData: false,
                    contentType: false,
                    success: function (response) {
                        if (response.success) {
                            progressbarLabel.text('Complete');
                            progressbarDiv.fadeOut(2000);
                            Popup.dialog('close');

                            window.location.href = '/Reconciliation/BaBsMy_View/';
                            //dataTable.ajax.reload();

                            $.notify(response.message, {
                                globalPosition: "top center",
                                className: "success"
                            })

                        }
                        else {

                            progressbarLabel.text('Complete');
                            progressbarDiv.fadeOut(1000);
                            $.notify(response.message, {

                                globalPosition: "top center",
                                className: "error"
                            })

                        }

                    },
                    error: function (err) {
                        alert(err.statusText);
                    }
                });
                progressbarLabel.text('@Deneme.Resource.Uploading');
                progressbarDiv.progressbar({
                    value: false
                }).fadeIn(500);
            }
            return false;
        }
        function Delete(id) {
            if(confirm('@Deneme.Resource.DeleteConfirmation'))
            {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Delete_BaBsExcel", "BaBsReconciliation")/' + id,
                    success: function (data) {
                        if (data.success) {
                            dataTable.ajax.reload();

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            })

                        }
                        else {
                            dataTable.ajax.reload();

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "error"
                            })

                        }
                    }

                });
            }
        }
        function Show(id) {

            window.location.href = '/BaBsReconciliation/Show_BaBsExcel/' + id;
        }

                </script>
            }
       

</body>

Deneme/Views/BaBsReconciliation/Show_BaBsExcel.cshtml
@{
    ViewBag.Title = "Show_FAEY";
}
<body onload="Show()">
    <div class="row">
        <div class="col-sm-12">
            <div class="page-title-box">
                <div class="btn-group pull-right">
                    <ol class="breadcrumb hide-phone p-0 m-0">
                        <li class="breadcrumb-item"><a href="#">Mutabakatcim</a></li>
                        <li class="breadcrumb-item"><a href="@Url.Action("BaBsMY_View", "Reconciliation")">@Deneme.Resource.Reconciliation</a></li>
                        <li class="breadcrumb-item"><a href="@Url.Action("BaBsExcel_View", "BaBsReconciliation")">Excelden Mutabakat Oluştur</a></li>
                        <li class="breadcrumb-item active">@Deneme.Resource.Show</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <br />

    @*<a class="btn btn-success" style="margin-bottom:10px;" onclick="PopupForm('@Url.Action("Show_FAEY","Excel")')"><i class="fa fa-plus"></i> Add New</a>*@

    <table id="BillTemplate" class="display nowrap table table-striped table-bordered" style="width:100%;">
        <thead>
            <tr>
                <th>@Deneme.Resource.CurrentCode</th>
                <th>@Deneme.Resource.CurrentName</th>
                <th>@Deneme.Resource.IdentificationNumber</th>
                <th>@Deneme.Resource.TaxNumber</th>
                <th>@Deneme.Resource.VatExcluded</th>
                <th>@Deneme.Resource.DocumentNumber</th>

            </tr>
        </thead>
    </table>

    @section scripts{
        <script>

            var Popup, dataTable;
            window.onload = function Show() {
                dataTable = $("#BillTemplate").DataTable({
                    responsive: {
                        details: {
                            renderer: function (api, rowIdx, columns) {
                                var data = $.map(columns, function (col, i) {
                                    return col.hidden ?
                                        '<tr data-dt-row="' + col.rowIndex + '" data-dt-column="' + col.columnIndex + '">' +
                                        '<td>' + col.title + ':' + ' </td> ' +
                                        '<td>' + col.data + ' </td>' +
                                        '</tr>' :
                                        '';
                                }).join('');

                                return data ?
                                    $('<table/>').append(data) :
                                    false;
                            }
                        }
                    },
                "ajax": {
                    "url": "/BaBsReconciliation/Show_BaBsExcelView/"+@ViewBag.FaturaId,
                    "type": "GET",
                    "datatype": "json",
                    "style":"margin-left:50px"
                },
                "columns": [
                    { "data": "CariKodu" },
                    { "data": "CariAdı" },
                    { "data": "TcKimlikNo" },
                    { "data": "VergiNo" },
                    { "data": "KdvHariçTutar" },
                    { "data": "BelgeSayısı" },
                ],
                "language": {

                     "info": "@Deneme.Resource.Info",
                    "infoEmpty": "@Deneme.Resource.InfoEmpty",
                    "infoFiltered": "@Deneme.Resource.InfoFiltered",
                    "lengthMenu": "@Deneme.Resource.LengthMenu",
                    "loadingRecords": "@Deneme.Resource.LoadingRecords",
                    "zeroRecords": "@Deneme.Resource.ZeroRecords",
                    "search": "@Deneme.Resource.Search",
                    "emptyTable": "@Deneme.Resource.EmptyTable",
                    "paginate": {

                        "next": "@Deneme.Resource.Next",
                        "previous": "@Deneme.Resource.Previous"
                    },
                }
            });
            }

        </script>
    }
    <br /><br />
</body>