Deneme/Controllers/SubUserOperationsController.cs
using Deneme.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Deneme.Controllers
{
    public class SubUserOperationsController : MyBaseController
    {
        #region Sub kullanıcı görüntüle
        [Authorize]
        public ActionResult SUOP_View()
        {

            return View();
        }

        [Authorize]
        public ActionResult SUOP()
        {
            using (YirmibesYazilimMutabakatEntities1 dc = new YirmibesYazilimMutabakatEntities1())
            {
                //string[] Keys = User.Identity.Name.Split(',');
                int UserID = Convert.ToInt32(User.Identity.Name);
                var user = dc.SubUser.Where(a => a.Yetkili == UserID).ToList();
                return Json(new { data = user }, JsonRequestBehavior.AllowGet);
            }
        }
        #endregion

        #region Sub ekle-düzenle
        [HttpGet]
        [Authorize]
        public ActionResult AddOrEdit_SUOP(int id = 0)
        {
            if (id == 0)
                return View(new SubUser());
            else
            {
                using (YirmibesYazilimMutabakatEntities1 db = new YirmibesYazilimMutabakatEntities1())
                {
                    return View(db.SubUser.Where(x => x.ID == id).FirstOrDefault<SubUser>());
                }
            }
        }

        [HttpPost]
        [Authorize]
        public ActionResult AddOrEdit_SUOP(SubUser sub)
        {
            //string[] Keys = User.Identity.Name.Split(',');
            int UserID = Convert.ToInt32(User.Identity.Name);
            using (YirmibesYazilimMutabakatEntities1 db = new YirmibesYazilimMutabakatEntities1())
            {
                sub.Yetkili = UserID;
                sub.Password = Crypto.Hash(sub.Password);
                sub.ConfirmPassword = Crypto.Hash(sub.ConfirmPassword);
                if (sub.ID == 0)
                {
                    var isExist = IsEmailExist(sub.Email);
                    if (isExist)
                    {
                        ModelState.AddModelError("EmailExist", "Email already exist");
                        return Json(new { success = false, message = Deneme.Resource.EmailExist }, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        db.SubUser.Add(sub);
                        db.SaveChanges();
                        return Json(new { success = true, message = Deneme.Resource.SavedSuccessfully }, JsonRequestBehavior.AllowGet);
                    }
                }
                else
                {
                    db.Entry(sub).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    return Json(new { success = true, message = Deneme.Resource.UpdatedSuccessfully }, JsonRequestBehavior.AllowGet);
                }
            }
        }

        [NonAction]
        public bool IsEmailExist(string emailID)
        {
            using (YirmibesYazilimMutabakatEntities1 dc = new YirmibesYazilimMutabakatEntities1())
            {

                var u = dc.SiteUser.Where(a => a.Email == emailID).FirstOrDefault();
                var v = dc.SubUser.Where(a => a.Email == emailID).FirstOrDefault();
                return v != null || u != null;
            }
        }
        #endregion

        #region delete sub 
        [HttpPost]
        [Authorize]
        public ActionResult Delete_SUOP(int id)
        {
            using (YirmibesYazilimMutabakatEntities1 db = new YirmibesYazilimMutabakatEntities1())
            {
                SubUser sub = db.SubUser.Where(x => x.ID == id).FirstOrDefault<SubUser>();
                db.SubUser.Remove(sub);
                db.SaveChanges();
                return Json(new { success = true, message = Deneme.Resource.DeletedSuccessfully }, JsonRequestBehavior.AllowGet);
            }
        }
        #endregion

        #region Yetkilendir 
        [HttpGet]
        [Authorize]
        public ActionResult Authorization_SUOP()
        {
            //string[] Keys = User.Identity.Name.Split(',');
            int UserID = Convert.ToInt32(User.Identity.Name);
            using (YirmibesYazilimMutabakatEntities1 db = new YirmibesYazilimMutabakatEntities1())
            {
                var companyInfo = db.Company.Where(a => a.KullanıcıID == UserID).ToList();
             

                List<SelectListItem> CompanyInformations = (from item in companyInfo
                                                          select new SelectListItem
                                                          {
                                                              Text = item.CompanyName,
                                                              Value = item.CompanyId.ToString()
                                                          }).ToList();

                ViewBag.CompanyId = CompanyInformations;
         
            }

            return View();

        }        

        [HttpPost]
        [Authorize]
        public ActionResult Authorization_SUOP(Yetki yetki, int id)
        {
            using (YirmibesYazilimMutabakatEntities1 db = new YirmibesYazilimMutabakatEntities1()) {
                var company = db.Company.Where(x => x.CompanyId == yetki.CompanyId).FirstOrDefault();
                Yetki isExist = db.Yetki.Where(x => x.UserID == id && x.CompanyId == yetki.CompanyId).FirstOrDefault<Yetki>();
                if (isExist !=null)
                {
                    db.Yetki.Remove(isExist);
                    db.SaveChanges();

                }
                //var sub = db.SubUser.Where(x => x.ID == id).FirstOrDefault();
                var Default = db.Yetki.Where(x => x.UserID == id && x.isDefault == true).FirstOrDefault();
                if(Default == null)
                {
                    yetki.isDefault = true;
                }
                yetki.UserID = id;
                string YetkiListe =Convert.ToInt16(yetki.BaOluştur) + "," + Convert.ToInt16(yetki.BaDüzenle)+ "," + Convert.ToInt16(yetki.BaMailGönder) + "," + Convert.ToInt16(yetki.BaSil)+ "," + Convert.ToInt16(yetki.BaSmsGönder)+ "," + Convert.ToInt16(yetki.BsOluştur) + "," + Convert.ToInt16(yetki.BsDüzenle) + "," + Convert.ToInt16(yetki.BsMailGönder) + "," + Convert.ToInt16(yetki.BsSil) + "," + Convert.ToInt16(yetki.BsSmsGönder)+ "," + Convert.ToInt16(yetki.CariOluştur) + "," + Convert.ToInt16(yetki.CariDüzenle) + "," + Convert.ToInt16(yetki.CariMailGönder)+ "," + Convert.ToInt16(yetki.CariSil)+ "," + Convert.ToInt16(yetki.CariSmsGönder);
                  yetki.Yetkiler = YetkiListe;
                yetki.CompanyName = company.CompanyName;
                db.Yetki.Add(yetki);
                db.SaveChanges();
            }
            return Json(new { success = true, message = Deneme.Resource.UpdatedSuccessfully }, JsonRequestBehavior.AllowGet);

        }
        #endregion

        #region Yetkileri göster

        //[HttpGet]
        //[Authorize]
        //public ActionResult Show_AuthView(int id)
        //{

        //    using (YirmibesYazilimMutabakatEntities1 dc = new YirmibesYazilimMutabakatEntities1())
        //    {
        //        var v = dc.FaturaBilgileriExcel.Where(a => a.FaturaBilgileriId == id).ToList();
        //        var jsonResult = Json(new { data = v }, JsonRequestBehavior.AllowGet);
        //        jsonResult.MaxJsonLength = int.MaxValue;
        //        return jsonResult;
        //    }

        //}

        [HttpGet]
        [Authorize]
        public ActionResult Show_Auth(int id)
        {
            //ViewBag.AuthId = id;
            using (YirmibesYazilimMutabakatEntities1 dc = new YirmibesYazilimMutabakatEntities1())
            {
                List<Company> company = new List<Company>();
                var auths = dc.Yetki.Where(a => a.UserID == id).ToList();
                foreach (var item in auths)
                {
                     var c = dc.Company.Where(a => a.CompanyId == item.CompanyId).FirstOrDefault();
                     company.Add(c);
                }
                ViewBag.auths = auths;
                ViewBag.company = company;

                return View();
            }
        }
        #endregion
    }
}

Deneme/Views/SubUserOperations/AddorEdit_SUOP.cshtml
@model Deneme.Models.SubUser
@{
    /**/

    /**/

    Layout = null;
}

@using (Html.BeginForm("AddorEdit_SUOP", "SubUserOperations", FormMethod.Post, new { onsubmit = "return SubmitForm(this)" }))
{
    @Html.HiddenFor(model => model.ID)
    <div class="block push-bit">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <form>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label class="control-label " for="Email">@Deneme.Resource.Email * </label>
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "required form-control" }})
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>

                <div class="form-group col-md-6">
                    <label class="control-label " for="Username">@Deneme.Resource.Username * </label>
                    @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "required form-control"} })
                    @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label class="control-label " for="Password">@Deneme.Resource.Password * </label>
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "required form-control" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })

                </div>
                <div class="form-group col-md-6">
                    <label class="control-label " for="ConfirmPassword">@Deneme.Resource.ConfirmPassword * </label>
                    @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = " form-control" } })
                    @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })

                </div>

            </div>
            <div class="form-group text-center m-t-15 ">
                <button class="btn btn-danger btn-block text-uppercase waves-effect waves-light"
                        type="submit">
                    @Deneme.Resource.Save
                </button>
            </div>
        </form>
    </div>

}

Deneme/Views/SubUserOperations/Authorization_SUOP.cshtml
@model Deneme.Models.Yetki
@{

    Layout = null;
}
<link href="assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
@using (Html.BeginForm("Authorization_SUOP", "SubUserOperations", FormMethod.Post, new { onsubmit = "return SubmitForm(this)" }))
{
    @Html.HiddenFor(model => model.YetkiID)

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @*<div class="row">

        <div class="col-lg-6">*@

    @*<h4 class="m-t-0 header-title">Contextual classes</h4>
        <p class="text-muted font-14 m-b-20">
            Use contextual classes to color table rows or individual cells.
        </p>*@
    <div class="form-row">
        <table class="table table-bordered table-hover col-md-12">
            <tbody>
                <tr class="table-warning">
                    <th scope="row">Ba</th>
                    <td> @Html.CheckBoxFor(m => m.BaOluştur) @Deneme.Resource.Create</td>
                    <td> @Html.CheckBoxFor(m => m.BaDüzenle)  @Deneme.Resource.Edit</td>
                    <td> @Html.CheckBoxFor(m => m.BaMailGönder)  @Deneme.Resource.SendMail</td>
                    <td> @Html.CheckBoxFor(m => m.BaSil)  @Deneme.Resource.Delete</td>
                    <td> @Html.CheckBoxFor(m => m.BaSmsGönder)  @Deneme.Resource.SendSms</td>
                </tr>
                <tr class="table-danger">
                    <th scope="row">Bs</th>
                    <td> @Html.CheckBoxFor(m => m.BsOluştur)   @Deneme.Resource.Create</td>
                    <td> @Html.CheckBoxFor(m => m.BsDüzenle)   @Deneme.Resource.Edit</td>
                    <td> @Html.CheckBoxFor(m => m.BsMailGönder)  @Deneme.Resource.SendMail</td>
                    <td> @Html.CheckBoxFor(m => m.BsSil)  @Deneme.Resource.Delete</td>
                    <td> @Html.CheckBoxFor(m => m.BsSmsGönder)  @Deneme.Resource.SendSms</td>
                </tr>
                <tr class="table-success">
                    <th scope="row">Cari</th>
                    <td> @Html.CheckBoxFor(m => m.CariOluştur)   @Deneme.Resource.Create</td>
                    <td> @Html.CheckBoxFor(m => m.CariDüzenle)   @Deneme.Resource.Edit</td>
                    <td> @Html.CheckBoxFor(m => m.CariMailGönder)   @Deneme.Resource.SendMail</td>
                    <td> @Html.CheckBoxFor(m => m.CariSil)  @Deneme.Resource.Delete</td>
                    <td> @Html.CheckBoxFor(m => m.CariSmsGönder)  @Deneme.Resource.SendSms</td>
                </tr>
            </tbody>
        </table>
    </div>
        <div class="form-row">
            <div class="col-md-12">
                @Html.DropDownList("CompanyId", null, Deneme.Resource.SelectCompany, new { @class = "required form-control" })
                @Html.ValidationMessageFor(model => model.CompanyId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-row">
            <div class="form-group text-center m-t-15 col-md-12">
                <button class="btn btn-danger btn-block text-uppercase waves-effect waves-light"
                        type="submit">
                    @Deneme.Resource.Save
                </button>
            </div>
        </div>


        <script src="assets/js/bootstrap.min.js"></script>
        }

Deneme/Views/SubUserOperations/SUOP_View.cshtml
@{
    ViewBag.Title = "User Operations";
}
<body>
    <div class="row">
        <div class="col-sm-12">
            <div class="page-title-box">
                <div class="btn-group pull-right">
                    <ol class="breadcrumb hide-phone p-0 m-0">
                        <li class="breadcrumb-item"><a href="#">Mutabakatcim</a></li>

                        <li class="breadcrumb-item active">@Deneme.Resource.Authorize</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <br />

    <a class="btn btn-success" style="margin-bottom:10px;" onclick="PopupForm('@Url.Action("AddOrEdit_SUOP","SubUserOperations")')"><i class="fa fa-plus"></i> @Deneme.Resource.AddNew</a>
    <table id="BillTemplate" class="display nowrap table table-striped table-bordered" style="width:100%;">
        <thead>
            <tr>

                <th data-priority="2">@Deneme.Resource.Username</th>
                <th data-priority="3">@Deneme.Resource.Email</th>
                <th data-priority="1"></th>

            </tr>
        </thead>
    </table>

    @section scripts{


        <script>
        var Popup, dataTable;
        $(document).ready(function () {
            responsive: true
            dataTable = $("#BillTemplate").DataTable({
                responsive: {
                    details: {
                        renderer: function (api, rowIdx, columns) {
                            var data = $.map(columns, function (col, i) {
                                return col.hidden ?
                                    '<tr data-dt-row="' + col.rowIndex + '" data-dt-column="' + col.columnIndex + '">' +
                                    '<td>' + col.title + ':' + ' </td> ' +
                                    '<td>' + col.data + ' </td>' +
                                    '</tr>' :
                                    '';
                            }).join('');

                            return data ?
                                $('<table/>').append(data) :
                                false;
                        }
                    }
                },
                "ajax": {
                    "url": "/SubUserOperations/SUOP",
                    "type": "GET",
                    "datatype": "json",
                    "style":"margin-left:50px"
                },
                "columns": [
                    { "data": "Username" },
                    { "data": "Email" },


                    {"data":"ID" , "render" : function (data) {
                        return "<a class='btn btn-default btn-sm' onclick=PopupForm('@Url.Action("AddOrEdit_SUOP", "SubUserOperations")/" + data + "')><i class='fa fa-pencil'></i> @Deneme.Resource.Edit</a><a class='btn btn-primary btn-sm' style='margin-left:5px' onclick=PopupForm('@Url.Action("Authorization_SUOP", "SubUserOperations")/" + data + "')><i class='fa fa-user-secret'></i>  @Deneme.Resource.Authorize</a><a class='btn btn-danger btn-sm' style='margin-left:5px' onclick=Delete("+data+")><i class='fa fa-trash'></i> @Deneme.Resource.Delete</a><a class='btn btn-info btn-sm' style='margin-left:5px' onclick=Show("+data+")><i class='fa fa-trash'></i> @Deneme.Resource.Show</a>";
                    },
                        "orderable": false,
                        "searchable": false,
                        "width":"150px"
                    }

                ],
                "language": {

                    "info": "@Deneme.Resource.Info",
                    "infoEmpty": "@Deneme.Resource.InfoEmpty",
                    "infoFiltered": "@Deneme.Resource.InfoFiltered",
                    "lengthMenu": "@Deneme.Resource.LengthMenu",
                    "loadingRecords": "@Deneme.Resource.LoadingRecords",
                    "zeroRecords": "@Deneme.Resource.ZeroRecords",
                    "search": "@Deneme.Resource.Search",
                    "emptyTable": "@Deneme.Resource.EmptyTable1 <b>@Deneme.Resource.AddNew</b>  @Deneme.Resource.EmptyTable2",
                    "paginate": {

                        "next": "@Deneme.Resource.Next",
                        "previous": "@Deneme.Resource.Previous"
                    },

                }
            });
        });

        function PopupForm(url) {
            var formDiv = $('<div/>');
            $.get(url)
            .done(function (response) {
                formDiv.html(response);

                Popup = formDiv.dialog({
                    show: {
                        effect: "blind",
                        duration: 600
                    },
                    hide: {
                        effect: "blind",
                        duration: 600
                    },
                    autoOpen: true,
                    modal:true,
                    resizable: false,
                    title: '@Deneme.Resource.DialogSubUser',
                    height: 345,
                    width: 900,
                    close: function () {
                        Popup.dialog('destroy').remove();
                    }
                });
            });
        }

        function SubmitForm(form) {
            $.validator.unobtrusive.parse(form);
            if($(form).valid()){
                $.ajax({
                    type : "POST",
                    url : form.action,
                    data : $(form).serialize(),
                    success : function (data) {
                        if (data.success) {
                            Popup.dialog('close');
                            dataTable.ajax.reload();

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            })

                        }
                        else {

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "error"
                            })

                        }
                    }
                });
            }
            return false;
        }

        function Delete(id) {
            if(confirm('@Deneme.Resource.DeleteConfirmation'))
            {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Delete_SUOP", "SubUserOperations")/' + id,
                    success: function (data) {
                        if (data.success)
                        {
                            dataTable.ajax.reload();

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            })

                        }

                    }

                });
            }
        }
        function Show(id) {

            window.location.href = '/SubUserOperations/Show_Auth/' + id;
        }

        </script>
    }
</body>