Deneme/Controllers/CurrentReconciliationTemplateController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Deneme.Models;
using System.Data;

namespace Deneme.Controllers
{
    public class CurrentReconciliationTemplateController : MyBaseController
    {
        #region C.M.S
        [HttpGet]
        [Authorize]
        public ActionResult AddOrEdit_CMS(int id = 0)
        {
            if (id == 0)
                return View(new Şablon_CariMutabakat());
            else
            {
                using (YirmibesYazilimMutabakatEntities1 db = new YirmibesYazilimMutabakatEntities1())
                {
                    return View(db.Şablon_CariMutabakat.Where(x => x.ŞablonId == id).FirstOrDefault<Şablon_CariMutabakat>());
                }
            }
        }

        [HttpPost]
        [Authorize]
        public ActionResult AddOrEdit_CMS(Şablon_CariMutabakat fatura)
        {
            //string[] Keys = User.Identity.Name.Split(',');
            int UserID = Convert.ToInt32(User.Identity.Name);
            int SelectedCompanyID = Convert.ToInt32(Server.HtmlEncode(Request.Cookies["UserOp"]["CompanyId"]));
            //if (Session["SelectedCompanyID"] != null)
            //{
            //    SelectedCompanyID = Convert.ToInt32(Session["SelectedCompanyID"]);
            //}
            //else
            //{
            //    SelectedCompanyID = Convert.ToInt32(Keys[1]);
            //}
            using (YirmibesYazilimMutabakatEntities1 db = new YirmibesYazilimMutabakatEntities1())
            {
                fatura.KullanıcıId = UserID;
                fatura.OluşturmaTarihi = Convert.ToString(DateTime.Now);
                fatura.CompanyId = SelectedCompanyID;
                if (fatura.ŞablonId == 0)
                {
                    db.Şablon_CariMutabakat.Add(fatura);
                    db.SaveChanges();
                    return Json(new { success = true, message = Deneme.Resource.SavedSuccessfully }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    db.Entry(fatura).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    return Json(new { success = true, message = Deneme.Resource.UpdatedSuccessfully }, JsonRequestBehavior.AllowGet);
                }
            }
        }

        [HttpPost]
        [Authorize]
        public ActionResult Delete_CMS(int id)
        {
            using (YirmibesYazilimMutabakatEntities1 db = new YirmibesYazilimMutabakatEntities1())
            {
                Şablon_CariMutabakat fatura = db.Şablon_CariMutabakat.Where(x => x.ŞablonId == id).FirstOrDefault<Şablon_CariMutabakat>();
                db.Şablon_CariMutabakat.Remove(fatura);
                db.SaveChanges();
                return Json(new { success = true, message = Deneme.Resource.DeletedSuccessfully }, JsonRequestBehavior.AllowGet);
            }
        }

        [Authorize]
        public ActionResult CMS_View()
        {

            return View();
        }

        [Authorize]
        public ActionResult CMS()
        {
            //string[] Keys = User.Identity.Name.Split(',');
            int UserID = Convert.ToInt32(User.Identity.Name);
            int SelectedCompanyID = Convert.ToInt32(Server.HtmlEncode(Request.Cookies["UserOp"]["CompanyId"]));
            //if (Session["SelectedCompanyID"] != null)
            //{
            //    SelectedCompanyID = Convert.ToInt32(Session["SelectedCompanyID"]);
            //}
            //else
            //{
            //    SelectedCompanyID = Convert.ToInt32(Keys[1]);
            //}
            using (YirmibesYazilimMutabakatEntities1 dc = new YirmibesYazilimMutabakatEntities1())
            {

                var CariMutabakatŞablonu = dc.Şablon_CariMutabakat.Where(a => a.KullanıcıId == UserID && a.CompanyId == SelectedCompanyID).ToList();
                return Json(new { data = CariMutabakatŞablonu }, JsonRequestBehavior.AllowGet);
            }
        }
        #endregion
    }
}

Deneme/Views/CurrentReconciliationTemplate/AddOrEdit_CMS.cshtml
@model Deneme.Models.Şablon_CariMutabakat
@{
    /**/

    /**/

    Layout = null;
}

@using (Html.BeginForm("AddOrEdit_CMS", "CurrentReconciliationTemplate", FormMethod.Post, new { onsubmit = "return SubmitForm(this)" }))
{
    @Html.HiddenFor(model => model.ŞablonId)
    <div class="block push-bit">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <form>
            <div class="form-row">
                <div class="form-group col-md-8">
                    @*@Html.LabelFor(model => model.ŞablonAdı, htmlAttributes: new { @class = "control-label col-md-2" })*@
                    <label class="control-label " for="TemplateName">@Deneme.Resource.TemplateName * </label>
                    @Html.EditorFor(model => model.ŞablonAdı, new { htmlAttributes = new { @class = "required form-control" } })
                    @Html.ValidationMessageFor(model => model.ŞablonAdı, "", new { @class = "text-danger" })

                </div>
                <div class="form-group col-md-4">
                    @*@Html.LabelFor(model => model.ŞablonAdı, htmlAttributes: new { @class = "control-label col-md-2" })*@
                    <label class="control-label " for="StartLine">@Deneme.Resource.StartLine * </label>
                    @Html.EditorFor(model => model.BaşlangıçSatırı, new { htmlAttributes = new { @class = "required form-control" } })
                    @Html.ValidationMessageFor(model => model.BaşlangıçSatırı, "", new { @class = "text-danger" })

                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-4">
                    @*@Html.LabelFor(model => model.CariKodu, htmlAttributes: new { @class = "control-label col-md-2" })*@
                    <label class="control-label " for="CurrentCode">@Deneme.Resource.CurrentCode * </label>
                    @Html.DropDownList("CariKodu", new SelectList(Enum.GetValues(typeof(Deneme.Models.Şablon_CariMutabakat.Alphabet))), Deneme.Resource.Select + ' ' + Deneme.Resource.CurrentCode + ' ' + Deneme.Resource.Select2, new { @class = "required form-control" })
                    @Html.ValidationMessageFor(model => model.CariKodu, "", new { @class = "text-danger" })

                </div>

                <div class="form-group col-md-4">
                    @*@Html.LabelFor(model => model.CariAdı, htmlAttributes: new { @class = "control-label col-md-2" })*@
                    <label class="control-label " for="CurrentName">@Deneme.Resource.CurrentName * </label>
                    @Html.DropDownList("CariAdı", new SelectList(Enum.GetValues(typeof(Deneme.Models.Şablon_CariMutabakat.Alphabet))), Deneme.Resource.Select + ' ' + Deneme.Resource.CurrentName + ' ' + Deneme.Resource.Select2, new { @class = "required form-control" })
                    @Html.ValidationMessageFor(model => model.CariAdı, "", new { @class = "text-danger" })

                </div>

                <div class="form-group col-md-4">
                    @*@Html.LabelFor(model => model.VergiDairesi, htmlAttributes: new { @class = "control-label col-md-2" })*@
                    <label class="control-label " for="TaxOffice">@Deneme.Resource.TaxOffice * </label>
                    @Html.DropDownList("VergiDairesi", new SelectList(Enum.GetValues(typeof(Deneme.Models.Şablon_CariMutabakat.Alphabet))), Deneme.Resource.Select + ' ' + Deneme.Resource.TaxOffice + ' ' + Deneme.Resource.Select2, new { @class = "required form-control" })
                    @Html.ValidationMessageFor(model => model.VergiDairesi, "", new { @class = "text-danger" })

                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-4">
                    @*@Html.LabelFor(model => model.VergiNo, htmlAttributes: new { @class = "control-label col-md-2" })*@
                    <label class="control-label " for="TaxNumber">@Deneme.Resource.TaxNumber * </label>
                    @Html.DropDownList("VergiNo", new SelectList(Enum.GetValues(typeof(Deneme.Models.Şablon_CariMutabakat.Alphabet))), Deneme.Resource.Select + ' ' + Deneme.Resource.TaxNumber + ' ' + Deneme.Resource.Select2, new { @class = "required form-control" })
                    @Html.ValidationMessageFor(model => model.VergiNo, "", new { @class = "text-danger" })

                </div>

                <div class="form-group col-md-4">
                    @*@Html.LabelFor(model => model.KdvHariçTutar, htmlAttributes: new { @class = "control-label col-md-2" })*@
                    <label class="control-label " for="VatExcluded">@Deneme.Resource.VatExcluded * </label>
                    @Html.DropDownList("KdvHariçTutar", new SelectList(Enum.GetValues(typeof(Deneme.Models.Şablon_CariMutabakat.Alphabet))), Deneme.Resource.Select + ' ' + Deneme.Resource.VatExcluded + ' ' + Deneme.Resource.Select2, new { @class = "required form-control" })
                    @Html.ValidationMessageFor(model => model.KdvHariçTutar, "", new { @class = "text-danger" })

                </div>
                <div class="form-group col-md-4">
                    @*@Html.LabelFor(model => model.KdvHariçTutar, htmlAttributes: new { @class = "control-label col-md-2" })*@
                    <label class="control-label " for="VatValue">@Deneme.Resource.VatValue * </label>
                    @Html.DropDownList("KdvTutarı", new SelectList(Enum.GetValues(typeof(Deneme.Models.Şablon_CariMutabakat.Alphabet))), Deneme.Resource.Select + ' ' + Deneme.Resource.VatValue + ' ' + Deneme.Resource.Select2, new { @class = "required form-control" })
                    @Html.ValidationMessageFor(model => model.KdvTutarı, "", new { @class = "text-danger" })

                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    @*@Html.LabelFor(model => model.BelgeTarihi, htmlAttributes: new { @class = "control-label col-md-2" })*@
                    <label class="control-label " for="DocumentDate">@Deneme.Resource.DocumentDate * </label>
                    @Html.DropDownList("BelgeTarihi", new SelectList(Enum.GetValues(typeof(Deneme.Models.Şablon_CariMutabakat.Alphabet))), Deneme.Resource.Select + ' ' + Deneme.Resource.DocumentDate + ' ' + Deneme.Resource.Select2, new { @class = "required form-control" })
                    @Html.ValidationMessageFor(model => model.BelgeTarihi, "", new { @class = "text-danger" })

                </div>

                <div class="form-group col-md-6">
                    @*@Html.LabelFor(model => model.BelgeNumarası, htmlAttributes: new { @class = "control-label col-md-2" })*@
                    <label class="control-label " for="DocumentNumber">@Deneme.Resource.DocumentNumber * </label>
                    @Html.DropDownList("BelgeNumarası", new SelectList(Enum.GetValues(typeof(Deneme.Models.Şablon_CariMutabakat.Alphabet))), Deneme.Resource.Select + ' ' + Deneme.Resource.DocumentNumber + ' ' + Deneme.Resource.Select2, new { @class = "required form-control" })
                    @Html.ValidationMessageFor(model => model.BelgeNumarası, "", new { @class = "text-danger" })

                </div>
            </div>
            <div class="form-group text-center m-t-15 ">
                <button class="btn btn-danger btn-block text-uppercase waves-effect waves-light"
                        type="submit">
                    @Deneme.Resource.Save
                </button>
            </div>
        </form>
    </div>

}

Deneme/Views/CurrentReconciliationTemplate/CMS_View.cshtml
@{
    ViewBag.Title = "Cari Mutabakat Şablonu";
}
<body>
    <div class="row">
        <div class="col-sm-12">
            <div class="page-title-box">
                <div class="btn-group pull-right">
                    <ol class="breadcrumb hide-phone p-0 m-0">
                        <li class="breadcrumb-item"><a href="#">Mutabakatcim</a></li>
                        <li class="breadcrumb-item"><a href="#">@Deneme.Resource.TemplateSettings</a></li>
                        <li class="breadcrumb-item active">@Deneme.Resource.CurrentReconciliationTemplate</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <br />

    <a class="btn btn-success" style="margin-bottom:10px;" onclick="PopupForm('@Url.Action("AddOrEdit_CMS","CurrentReconciliationTemplate")')"><i class="fa fa-plus"></i> @Deneme.Resource.AddNew</a>
    <table id="BillTemplate" class="display nowrap table table-striped table-bordered" style="width:100%;">
        <thead>
            <tr>
                <th></th>
                <th data-priority="2">@Deneme.Resource.TemplateName</th>
                <th data-priority="3">@Deneme.Resource.StartLine</th>
                <th>@Deneme.Resource.CurrentCode</th>
                <th>@Deneme.Resource.CurrentName</th>
                <th>@Deneme.Resource.TaxOffice</th>
                <th>@Deneme.Resource.TaxNumber</th>
                <th>@Deneme.Resource.VatExcluded</th>
                <th>@Deneme.Resource.VatValue</th>
                <th>@Deneme.Resource.DocumentDate</th>
                <th>@Deneme.Resource.DocumentNumber</th>
                <th data-priority="4">@Deneme.Resource.TemplateCreationDate</th>
                <th data-priority="1"></th>
            </tr>
        </thead>
    </table>


    @section scripts{

        <script>
        var Popup, dataTable;
            $(document).ready(function () {
                dataTable = $("#BillTemplate").DataTable({
                    responsive: {
                        details: {
                            renderer: function (api, rowIdx, columns) {
                                var data = $.map(columns, function (col, i) {
                                    return col.hidden ?
                                        '<tr data-dt-row="' + col.rowIndex + '" data-dt-column="' + col.columnIndex + '">' +
                                        '<td>' + col.title + ':' + '</td> ' +
                                        '<td>' + col.data + '</td>' +
                                        '</tr>' :
                                        '';
                                }).join('');

                                return data ?
                                    $('<table/>').append(data) :
                                    false;
                            }
                        }
                     },
                "ajax": {
                    "url": "/CurrentReconciliationTemplate/CMS",
                    "type": "GET",
                    "datatype": "json",
                    "style":"margin-left:50px"
                },
                "columns": [
                    {
                        "className": 'control',
                        "orderable": false,
                        "data": null,
                        "defaultContent": ''
                    },
                    { "data": "ŞablonAdı" },
                    { "data": "BaşlangıçSatırı" },
                    { "data": "CariKodu" },
                    { "data": "CariAdı" },
                    { "data": "VergiDairesi" },
                    { "data": "VergiNo" },
                    { "data": "KdvHariçTutar" },
                    { "data": "KdvTutarı" },
                    { "data": "BelgeTarihi" },
                    { "data": "BelgeNumarası" },
                    { "data": "OluşturmaTarihi" },
                    {"data":"ŞablonId" , "render" : function (data) {
                        return "<a class='btn btn-default btn-sm' onclick=PopupForm('@Url.Action("AddOrEdit_CMS", "CurrentReconciliationTemplate")/" + data + "')><i class='fa fa-pencil'></i> @Deneme.Resource.Edit</a><a class='btn btn-danger btn-sm' style='margin-left:5px' onclick=Delete("+data+")><i class='fa fa-trash'></i> @Deneme.Resource.Delete</a>";
                    },
                        "orderable": false,
                        "searchable":false,
                        "width":"150px"
                    }

                ],
                "language": {

                    "info": "@Deneme.Resource.Info",
                    "infoEmpty": "@Deneme.Resource.InfoEmpty",
                    "infoFiltered": "@Deneme.Resource.InfoFiltered",
                    "lengthMenu": "@Deneme.Resource.LengthMenu",
                    "loadingRecords": "@Deneme.Resource.LoadingRecords",
                    "zeroRecords": "@Deneme.Resource.ZeroRecords",
                    "search": "@Deneme.Resource.Search",
                    "emptyTable": "@Deneme.Resource.EmptyTable1 <b>@Deneme.Resource.AddNew</b>  @Deneme.Resource.EmptyTable2",
                    "paginate": {

                        "next": "@Deneme.Resource.Next",
                        "previous": "@Deneme.Resource.Previous"
                    },
                }
            });
        });

        function PopupForm(url) {
            var formDiv = $('<div/>');
            $.get(url)
            .done(function (response) {
                formDiv.html(response);

                Popup = formDiv.dialog({
                    show: {
                        effect: "blind",
                        duration: 600
                    },
                    hide: {
                        effect: "blind",
                        duration: 600
                    },
                    autoOpen: true,
                    resizable: false,
                    title: '@Deneme.Resource.CurrentReconciliationTemplate',
                    height: 420,
                    width: 800,
                    close: function () {
                        Popup.dialog('destroy').remove();
                    }
                });
            });
        }

        function SubmitForm(form) {
            $.validator.unobtrusive.parse(form);
            if($(form).valid()){
                $.ajax({
                    type : "POST",
                    url : form.action,
                    data : $(form).serialize(),
                    success : function (data) {
                        if(data.success)
                        {
                            Popup.dialog('close');
                            dataTable.ajax.reload();

                            $.notify(data.message,{
                                globalPosition :"top center",
                                className : "success"
                            })

                        }
                    }
                });
            }
            return false;
        }

        function Delete(id) {
            if(confirm('@Deneme.Resource.DeleteConfirmation'))
            {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Delete_CMS", "CurrentReconciliationTemplate")/' + id,
                    success: function (data) {
                        if (data.success)
                        {
                            dataTable.ajax.reload();

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            })

                        }
                    }

                });
            }
            }

        </script>
    }
</body>